### ISSUE TITLE
Proposal: running clingon:run and not exit-ing when in a dumb terminal (like Slime)

### ISSUE THREAD

**Issue by vindarel** [dnaeon/clingon#12]
We can already test the args parsing with `clingon:parse-command-line <cmd> (list "of" "args"))`.

To run our application we must call `clingon:run <cmd>`, and this eventually calls `uiop:quit`. So, if we try this on the Lisp REPL, the Lisp connection is closed.

What about adding a simple heuristic to maybe *not* close the connection?

I have used this for some scripts: https://github.com/vindarel/termp/blob/master/termp.lisp It simply checks `(not (equalp "dumb" (uiop:getenv "TERM")))`, and that works for Emacs & Slime.

A global parameter could do, it would already allow to test a bit more our command during development. Something like

```lisp
CL-USER> (let ((clingon::*quit* nil))
           (clingon:run (cli/command)))
```

or use a hook? (I didn't explore them)

```lisp
CL-USER> (push clingon:*no-quit-hook* clingon:post-hooks)
CL-USER> (clingon:run …)
```

**Comment by vindarel** [comment]
> 'll have to think about it :)

ACK, glad you consider it.

---

(side note)

oh, and https://github.com/dnaeon/cl-jingle#directory-browser =>

    (jingle:serve-directory *app* "/docs" "~/Documents")

nice, I'll have to study it and maybe re-evaluate Clack-based apps… (my main issue is the lack of doc)

I'll mention this alternative, and I'd love if jingle was available to download as a binary.

> great work on CIEL!

Thanks! The newly added scripting thing gives it another dimension.

**Comment by dnaeon** [comment]
Merged, thanks!

**Comment by vindarel** [comment]
Hello, I am reading a case where they had to find a workaround of this (mis)feature: Clack brings in swank. And indeed, we sometimes want a running swank server to connect from our app.

```lisp
;; https://github.com/endatabas/endb/blob/1db9522610d59797374fe26d5b07d1b4d72dae4f/src/core.lisp
(defun main ()
  ;; clingon:exit-error has a guard against existing the REPL, but clack brings in swank.
  (let ((*features* (remove :swank *features*))
        (app (endb-command)))
    (clingon:run app)))
```
