### ISSUE TITLE
About line breaks in the description

### ISSUE THREAD

**Issue by simendsjo** [dnaeon/clingon#17]
First off, I absolutely love Clingon! Feature rich, easy to use, and everything just works! Had to write my own `run` to avoid the global error handler, but everything has been smooth sailing otherwise. The documentation is also great!

So this is a minor nitpick: Is it possible to have line-breaks in the source code without them being added in the help output? If the `~Newline` directive was supported, I guess everything would work fine. If I have to keep everything on a single source lines, it becomes harder to maintain the documentation.

![image](https://github.com/dnaeon/clingon/assets/351519/10b4ed8a-e57d-45f7-970e-6bd5ecfe5ab2)
![image](https://github.com/dnaeon/clingon/assets/351519/4b8cc1c3-d754-485d-8e92-e9dd74bb4f78)

EDIT: I would think adding a little format here would do the trick: https://github.com/dnaeon/clingon/blob/master/src/command.lisp#L1038
I.e. `(wrap (format nil description))' instead of `(wrap description)'

Of course, this means the descriptions have to be aware of using `~`, which might be a bit intrusive..

**Comment by dnaeon** [comment]
Hey @simendsjo ,

Thanks for the kind words, happy to hear `clingon` serves you well :)

A solution for `long-description` would be to use `(format nil description) ...` before passing it to the `:long-description` initarg.

See here for example:

* https://github.com/dnaeon/clingon/blob/master/examples/demo/main.lisp#L74

Another possible solution would be to provide your own `CLINGON:COMMAND-LONG-DESCRIPTION` method, which does `(format nil ...)`, e.g.

``` lisp
(defmethod clingon:command-long-description ((command clingon:command))
  (with-slots (clingon.command::long-description) command
    (format nil clingon.command::long-description)))
```

Using this approach you can provide any `FORMAT` directive directly to the `:long-description` initarg.

Let me know what do you think.

Thanks!

**Comment by simendsjo** [comment]
Thanks! I actually just found the solution before looking back here ;) This is for the option description that was giving be problems:

```lisp
(defmethod clingon:option-description :around ((option clingon:option))
  (format nil (call-next-method option)))
```

![image](https://github.com/dnaeon/clingon/assets/351519/75325178-458b-4c9e-995f-51022fe52578)
![image](https://github.com/dnaeon/clingon/assets/351519/dc7b51ff-6574-40d9-a66c-8bab71bb5eb4)

**Comment by dnaeon** [comment]
Nice! :)
