### ISSUE TITLE
Question: Clingon and buildapp?

### ISSUE THREAD

**Issue by rpgoldman** [dnaeon/clingon#18]
I'm a fan of both clingon and Xach's buildapp.  Is there some way they can be made compatible?  Xach's buildapp calls its entrypoint with `argv` as argument.

I *think* that buildapp's argv could be passed to `clingon:parse-command-line`, but I don't know how I would take the return value of `clingon:parse-command-line` and run it.  

But I don't believe I can just invoke `clingon:run` on an app from a buildapp entrypoint, because the buildapp entrypoint expects to be handed arguments, but `run` expects to go out and get the arguments.

Any suggestions?  Even though I maintain it, I'm not a fan of ASDF's application building.  Thanks!

**Comment by dnaeon** [comment]
Hey @rpgoldman ,

I haven't used `buildapp`, so if you could provide some hints on what you have so far and what is not working I might be able to help out.

If you've got an example app I could see that would be even better.

Thanks,
Marin

**Comment by dnaeon** [comment]
Hey @rpgoldman ,

I've just documented how to use `buildapp` for building `clingon` apps.

See https://github.com/dnaeon/clingon/commit/6d8658ab0da59f831807e34c19742927413ab3da and https://github.com/dnaeon/clingon#buildapp

Let me know when you get a chance to test it out.

**Comment by rpgoldman** [comment]
Thank you very much, @dnaeon !  I'm sorry; I forgot to respond to this after I successfully used clingon with buildapp.  The documentation you added is exactly what was needed!

**Comment by dnaeon** [comment]
Hey @rpgoldman , glad to hear it works fine! :)
