### ISSUE TITLE
Save upper/lower case info in `clingon:command-arguments`

### ISSUE THREAD

**Issue by jcs090218** [dnaeon/clingon#27]
When,

```cl
(clingon:command-arguments cmd)
```

The arguments lose their upper/lower case information. 🤔

**Comment by dnaeon** [comment]
Hey there,

Can you please provide an example?

Thanks!

**Comment by jcs090218** [comment]
It turns out to be the `readtable-case` issue. 😅 

Sorry for the noise!It turns out to be the `readtable-case` issue. 😅 

Sorry for the noise! Fixed in https://github.com/cl-qob/cli/commit/e08c87b9bcec83ae393fc44af123785cb91584d8.
