### ISSUE TITLE
Simple question about README

### ISSUE THREAD

**Issue by rpgoldman** [dnaeon/clingon#8]
What does the empty `:import-from` clause in the `defpackage` for `:clingon.example.greet` do?  Isn't that a no-op?

**Comment by dnaeon** [comment]
Hey @rpgoldman ,

It is a no-op :) 

While it does nothing, I usually follow this style of explicitly "importing" the systems I will be working with. They also serve me as a form of visual indication that I need to `(ql:quickload ...)` some system, which is useful when sharing short snippets of code.

Also, I guess it's an old habit of me using other languages, which do require you to import stuff, before you use them, so I guess that's another reason (even though, not really applicable to the image-based development in CL).

**Comment by rpgoldman** [comment]
Thanks for the quick answer. I figured it was something like this, but wanted to be sure I wasn't missing anything!
